name: ankush_dev
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - content:/opt/blog/content:rw
    working_dir: /opt/blog/
    stop_grace_period: 1s
    restart: always
    ports:
      - "3000:3000"

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - content:/content
    environment:
      DOMAIN: "https://ankush.dev"
      EMAIL: "ankushmenat@gmail.com"
      LOG_FILE: "/data/access.log"


volumes:
  content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./content
