name: CI

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ hashFiles('**/Cargo.toml') }}
            cargo-

      - name: Cargo Target Cache
        uses: actions/cache@v3
        with:
          path: target
          key: cargo-target-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-target-${{ hashFiles('**/Cargo.toml') }}
            cargo-target-

      - name: Run tests
        run: |
          cd ${GITHUB_WORKSPACE}
          cargo build --verbose
          cargo run &

